### Tek satır if (One-liner if)

In [ ]:
koşul = 3

if koşul > 5:
    kelime = "Elma"
elif koşul > 7:
    pass
else:
    kelime = "Armut"
    print(kelime)

Armut


In [ ]:
kelime = "Elma" if koşul else "Armut" if koşul > 5 else "Çilek"

### Tek satır fonksiyon Lambda (One-liner function Lambda)

In [ ]:
def hello_world():
    return "Hello World"

hello_world()

'Hello World'

In [ ]:
def kare_alma(x):
    x = x ** 2
    return x

kare_alma(5)

25

In [ ]:
kare_al = lambda x: x**2
kare_al(5)

25

### map, reduce, filter, zip fonksiyonları

In [ ]:
sayılar = [1, 2, 3, 4, 5, 6, 7]
sayıların_kareleri = []

for sayı in sayılar:
    sayıların_kareleri.append(kare_al(sayı))
print(sayıların_kareleri)

[1, 4, 9, 16, 25, 36, 49]


In [ ]:
liste = [2,3,4]

def kare_al2(sayi23):
    return sayi **2

result = map(kare_al2,liste)
print(result)

In [ ]:
#map(function,iteration) 
sayıların_kareleri =  map(kare_al, sayılar)
print(sayıların_kareleri)
for sayı in sayıların_kareleri:
    print(sayı)


1
4
9
16
25
36
49


In [ ]:
from functools import reduce

sayılar = [1, 6, 3, 7, 10, 0]
print(reduce(lambda x,y: x if x > y else y, sayılar))

10


In [ ]:
def beşten_uzun(kelime):
    if len(kelime) > 5:
        return True
    else:
        return False
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']
uzun_isimler = filter(beşten_uzun, isimler)
print(uzun_isimler)
for isim in uzun_isimler:
    print(isim)

Necati
Mehmet


In [ ]:
sayılar = [0, 1, 2, 3, 4, 5]
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']


for i, j in zip(sayılar, isimler):
    print(i,j)


0 Oğuz
1 Ahmet
2 Necati
3 Ali
4 Mehmet
5 Ziya


### Assert anahtar kelimesi ( Assert keyword )

In [ ]:
yaş = input("Yaşınız:")
assert int(yaş) >= 0, "Yaşınız negatif olamaz"

Yaşınız:-2


AssertionError: Yaşınız negatif olamaz

### Üreteçler (Generators)

In [ ]:
def generator():
    i = 1
    print('Öncelikle bu basıldı')
    yield i

    i += 1
    print('Sonra bu')
    yield i

for eleman in generator():
    print("For döngüsü içinde:", eleman)


Öncelikle bu basıldı
For döngüsü içinde: 1
Sonra bu
For döngüsü içinde: 2


In [ ]:
a = 5

def outer():
    a = 3
    def inner():
        nonlocal a
        a += 5
        print("inner fonksiyon:", a)
    print("outer fonksiyon:", a)
    return inner()

outer()
inner()
print("global:", a)

outer fonksiyon: 3
inner fonksiyon: 8


NameError: name 'inner' is not defined

### Decorators

In [ ]:
#especially It is used for Flask and Django Framework
from datetime import datetime

def show_time(func):
    def wrapper(name):
        print("Time:", datetime.now().time())
        func(name)
    return wrapper

@show_time
def say_hi(name="John"):
    print("Hi {}!".format(name))

say_hi("Ahmet")

Time: 19:59:57.128105
Hi Ahmet!


In [ ]:
import time 
def calculate_time(func):
    def wrapper(numbers):
        start = time.time()
        end = time.time()
        result = func(numbers)
        print(func.__name__ + " " + str(end - start) + "HAHA")
        return result
    return wrapper

@calculate_time
def kare_al_wrapper(numbers):
    result = []
    for i in numbers:
        result.append(i ** 2)
    return result

@calculate_time
def kup_al_wrapper(numbers):
    result = []
    for i in numbers:
        result.append(i ** 3)
    return result

print(kare_al_wrapper(range(100)))
print(kup_al_wrapper(range(100)))

kare_al_wrapper 0.0HAHA
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]
kup_al_wrapper 0.0HAHA
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859, 8000, 9261, 10648, 12167, 13824, 15625, 17576, 19683, 21952, 24389, 27000, 29791, 32768, 35937, 39304, 42875, 46656, 50653, 54872, 59319, 64000, 68921, 74088, 79507, 85184, 91125, 97336, 103823, 110592, 117649, 125000, 132651, 140608, 148877, 157464, 166375, 175616, 185193, 195112, 205379, 2160

# Numpy



* Basic library used in scientific calculations

* Linear algebra, machine learning, data science

* Multi-dimensional arrays

* Fast access to multidimensional arrays

* The difference from the lists is having a fixed size.

![Scalar Vector Matrix Tensor](https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)

In [ ]:
import numpy as np

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(6,)


In [ ]:
liste= [1,2,3,4,5]
liste[3]

4

In [ ]:
print(a[3])

40


In [ ]:
type(a[3])

numpy.int32

In [ ]:
a[2] *= 2
print(a[2])

60


In [ ]:
a

array([10, 20, 60, 40, 50, 60])

In [ ]:
x = np.array([1,2,3])
y = x
z = np.copy(x)
z

array([1, 2, 3])

In [ ]:
x[0] = 10
x[0] == y[0]
x[0] == z[0]
z

array([1, 2, 3])

In [ ]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(b)
print(b.shape)
print(b.dtype)
print(type(b))

[[10 20 30]
 [40 50 60]]
(2, 3)
int32
<class 'numpy.ndarray'>


In [ ]:
a = np.array([10, 20, 30, 40, 50, 180])
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.80115264])

In [ ]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298])

In [ ]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456])

In [ ]:
#Calculate the exponential of all elements in the input array
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21, 1.48938420e+78])

In [ ]:
c = np.array([10, 20, 100, 40, 10, 60])
c

array([ 10,  20, 100,  40,  10,  60])

In [ ]:
np.max(c)

100

In [ ]:
np.min(c)

10

In [ ]:
#found the index of maximum element
np.argmax(c)

2

In [ ]:
np.mean(c)

40.0

In [ ]:
np.median(c)

30.0

In [ ]:
#standard deviation
np.std(c)

2.997941680718231

In [ ]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# axis=1 => Row
# axis=0 => Column
np.sum(b, axis = 0)

array([50, 70, 90])

In [ ]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
full = np.full((3, 3), 5)
print(full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#Identity matrix n*n
eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arange = np.arange(7)
print(arange)

arange = np.arange(0, 10)
print(arange)

arange = np.arange(0, 10, 2)
print(arange)

[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [ ]:
# Create randint
random = np.random.random((3, 3))
print(random)

[[0.51118639 0.84087018 0.15037286]
 [0.66320806 0.89214617 0.07764766]
 [0.44066875 0.59388301 0.78066343]]


In [ ]:
arr = np.random.randint(20, size=(5, 5))
print(arr)

[[ 0  2 14 17  0]
 [10  5  2 17  4]
 [17  5 17  6  4]
 [12 11  9 13  8]
 [ 9  1  5  9  0]]


In [ ]:
zeros*6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr

array([[ 0,  2, 14, 17,  0],
       [10,  5,  2, 17,  4],
       [17,  5, 17,  6,  4],
       [12, 11,  9, 13,  8],
       [ 9,  1,  5,  9,  0]])

In [ ]:
arr[3,2]

9

In [ ]:
arr[0:3, ::]
#arr[satır, sütun]

array([[ 0,  2],
       [10,  5],
       [17,  5]])

In [ ]:
arr[0:3, :2]

array([[ 0,  2],
       [10,  5],
       [17,  5]])

In [ ]:
arr[arr > 10]

array([14, 17, 17, 17, 17, 12, 11, 13])

In [ ]:
np.where(arr > 10)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 3, 3, 4]),
 array([0, 1, 2, 4, 0, 1, 2, 3, 1, 1, 4, 0]))

In [ ]:
np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]).reshape(2,6).shape

(2, 6)

In [ ]:
#inverse in lineer algebra
c = np.random.randint(10, size=(3, 3))
print(c)
c_inv = np.linalg.inv(c)
print(c_inv)

[[3 1 9]
 [7 6 5]
 [0 4 0]]
[[-0.10416667  0.1875     -0.25520833]
 [ 0.          0.          0.25      ]
 [ 0.14583333 -0.0625      0.05729167]]


## İç Çarpım (Dot product)
![Dot product](https://algebra1course.files.wordpress.com/2013/02/slide10.jpg)

credit: https://algebra1course.files.wordpress.com/

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a.shape)

(2, 3)


In [ ]:
b = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
print(a.shape)

(2, 3)


In [ ]:
axb = np.dot(a, b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
# Transpose
(b.T).shape

(3, 2)

In [ ]:
axb = np.dot(a, b.T)
print(axb)
print(axb.shape)

[[ 50  68]
 [122 167]]
(2, 2)
